{
  "formatVersion": "1.1",
  "component": {
    "group": "com.inkryptvideos.android",
    "module": "inkryptvideos-android",
    "version": "2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-2.8.aar",
          "url": "inkryptvideos-android-2.8.aar",
          "size": 156401,
          "sha512": "49a10f5360225d7cd721ca578ef55b1378a631a2923d4ba29e4aceb5a32646baf55db5ac0777e434d64c30d9cde894924aa33b34a015397a9fb9c082d5d41294",
          "sha256": "2099b9b9f1a810f66c123b0f342e635f795ec3659d4f48c4a88b780aed95ea1a",
          "sha1": "53e9222c9a16954ebe2fd7d919e9beabcaed3ddd",
          "md5": "5de21cf839f25aef731f5260f489b89c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.SmartToolFactory",
          "module": "Compose-Colorful-Sliders",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.0.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-2.8.aar",
          "url": "inkryptvideos-android-2.8.aar",
          "size": 156401,
          "sha512": "49a10f5360225d7cd721ca578ef55b1378a631a2923d4ba29e4aceb5a32646baf55db5ac0777e434d64c30d9cde894924aa33b34a015397a9fb9c082d5d41294",
          "sha256": "2099b9b9f1a810f66c123b0f342e635f795ec3659d4f48c4a88b780aed95ea1a",
          "sha1": "53e9222c9a16954ebe2fd7d919e9beabcaed3ddd",
          "md5": "5de21cf839f25aef731f5260f489b89c"
        }
      ]
    }
  ]
}
