{
  "formatVersion": "1.1",
  "component": {
    "group": "com.inkryptvideos.android",
    "module": "inkryptvideos-android",
    "version": "2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-2.8.aar",
          "url": "inkryptvideos-android-2.8.aar",
          "size": 226931,
          "sha512": "95f538d22f2934bfb3fe27229377c4e5f947c0b5c933656cdc163a4e08b78ced1461c0eb141bfe2d235b72801b3a3e95df872fb92c813a6083066ef022bb0c70",
          "sha256": "1941953e069a7274efb9271a9bbd47105e1e77f41c85a1672af3ca81eeeb319e",
          "sha1": "b908f210a5c522c733b84923a2682176728b5a06",
          "md5": "02e8bf92dd9138c8c017cd06efcaa42d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.SmartToolFactory",
          "module": "Compose-Colorful-Sliders",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.0.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-2.8.aar",
          "url": "inkryptvideos-android-2.8.aar",
          "size": 226931,
          "sha512": "95f538d22f2934bfb3fe27229377c4e5f947c0b5c933656cdc163a4e08b78ced1461c0eb141bfe2d235b72801b3a3e95df872fb92c813a6083066ef022bb0c70",
          "sha256": "1941953e069a7274efb9271a9bbd47105e1e77f41c85a1672af3ca81eeeb319e",
          "sha1": "b908f210a5c522c733b84923a2682176728b5a06",
          "md5": "02e8bf92dd9138c8c017cd06efcaa42d"
        }
      ]
    }
  ]
}
