{
  "formatVersion": "1.1",
  "component": {
    "group": "com.inkryptvideos.android",
    "module": "inkryptvideos-android",
    "version": "2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-2.8.aar",
          "url": "inkryptvideos-android-2.8.aar",
          "size": 1163,
          "sha512": "47aba9f2276ff1ebb817b24d7346acb194044f31eeb534b682b8d5c4260a389fcc990872ce63a4061304cd170eea4acd7733f193b1b818f45ee362021e53ee59",
          "sha256": "8b60921dc085e79c66197e6854c5bd725c04b13dce82a3eb16b14580a8a46d46",
          "sha1": "5bfaa3a3a080854299f22aeeaaa40a9076308c73",
          "md5": "ebc51cd5daf37fe811ebc35ef8e5641b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.SmartToolFactory",
          "module": "Compose-Colorful-Sliders",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.0.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-2.8.aar",
          "url": "inkryptvideos-android-2.8.aar",
          "size": 1163,
          "sha512": "47aba9f2276ff1ebb817b24d7346acb194044f31eeb534b682b8d5c4260a389fcc990872ce63a4061304cd170eea4acd7733f193b1b818f45ee362021e53ee59",
          "sha256": "8b60921dc085e79c66197e6854c5bd725c04b13dce82a3eb16b14580a8a46d46",
          "sha1": "5bfaa3a3a080854299f22aeeaaa40a9076308c73",
          "md5": "ebc51cd5daf37fe811ebc35ef8e5641b"
        }
      ]
    }
  ]
}
