{
  "formatVersion": "1.1",
  "component": {
    "group": "com.inkryptvideos.android",
    "module": "inkryptvideos-android",
    "version": "2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-2.9.aar",
          "url": "inkryptvideos-android-2.9.aar",
          "size": 156448,
          "sha512": "a65d73f954ef16b82937aced6a52b701c1d7c91d9355a3b34695daae58acec46b2eddd01ee79a58ab5aa4b6dcf284e79726ea9d0781fe6891c6f4590581f997e",
          "sha256": "c355be2815d20331ee27814fd75e984d7b44e641297492d104b1aa0b2c5682b8",
          "sha1": "c6851589a9c79fba7b9db135dbff9d5ab9164afd",
          "md5": "692db8c9413062bb1f990bea2c6d27ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.SmartToolFactory",
          "module": "Compose-Colorful-Sliders",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.0.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-2.9.aar",
          "url": "inkryptvideos-android-2.9.aar",
          "size": 156448,
          "sha512": "a65d73f954ef16b82937aced6a52b701c1d7c91d9355a3b34695daae58acec46b2eddd01ee79a58ab5aa4b6dcf284e79726ea9d0781fe6891c6f4590581f997e",
          "sha256": "c355be2815d20331ee27814fd75e984d7b44e641297492d104b1aa0b2c5682b8",
          "sha1": "c6851589a9c79fba7b9db135dbff9d5ab9164afd",
          "md5": "692db8c9413062bb1f990bea2c6d27ef"
        }
      ]
    }
  ]
}
