{
  "formatVersion": "1.1",
  "component": {
    "group": "com.inkryptvideos.android",
    "module": "inkryptvideos-android",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-3.0.aar",
          "url": "inkryptvideos-android-3.0.aar",
          "size": 194381,
          "sha512": "f7d68405b7512cd51cb39a5112beabee4eb95d5202d0e45fce24ac3b86d64c014b2c4383fd4610409e99f868eadebfd395e6d0103806ca7fccca744963edc527",
          "sha256": "2b1568a29362090fea8f081ad0d0f3b20d6c1b32cf1f5b2cc515b43e50317417",
          "sha1": "f579bf838d69ec0fc5e44a7a2a25f7e0a3416c9b",
          "md5": "4ae1bd58451237346d0e14e9d51adf5d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.0.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-3.0.aar",
          "url": "inkryptvideos-android-3.0.aar",
          "size": 194381,
          "sha512": "f7d68405b7512cd51cb39a5112beabee4eb95d5202d0e45fce24ac3b86d64c014b2c4383fd4610409e99f868eadebfd395e6d0103806ca7fccca744963edc527",
          "sha256": "2b1568a29362090fea8f081ad0d0f3b20d6c1b32cf1f5b2cc515b43e50317417",
          "sha1": "f579bf838d69ec0fc5e44a7a2a25f7e0a3416c9b",
          "md5": "4ae1bd58451237346d0e14e9d51adf5d"
        }
      ]
    }
  ]
}
